name: Autograding

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ environment
      run: sudo apt-get install g++

    - name: Compile program
      run: g++ src/main.cpp -o main

    - name: Run tests
      run: ./main < tests/test_input.txt > output.txt

    - name: Compare output
      run: diff output.txt tests/expected_output.txt
